### ISSUE TITLE
Error validating data: ... invalid type for io.k8s.api.core.v1.Container.args: got "map", expected "string"

### ISSUE THREAD

**Issue by jahsome** [qumine/charts#1]
Thanks for publishing this project; I have learned much from it :)

I am curious if there is any insight into the following error:

```
❯ helm install mc-ing qumine/ingress-controller
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec.containers[0].args[0]): invalid type for io.k8s.api.core.v1.Container.args: got "map", expected "string"
```

**Comment by kddige** [comment]
Can confirm. Experiencing the samme  the samme issue. - Did you fix it?

**Comment by kddige** [comment]
I think it might be related to the [deamonset.yml](https://github.com/qumine/charts/blob/master/charts/ingress-controller/templates/daemonset.yaml) file. Line 30 to 33. If the args are empty (Debug is "false") then it renders an empty property. I will try to fork the repo, and test it out on my own.

**Comment by kddige** [comment]
Forked it, got it working. Seems like there where a wrong line-indent in daemonset.yml file. Also, the image variabels seems incorrect. Check it out here; https://github.com/kddige/charts

**Comment by 0SkillAllLuck** [comment]
Thanks @kddige and @jahsome for the contribution. The next version of the ingress should fix the issue by no longer requiring args at all as env variables are a bit easier to use
