### ISSUE TITLE
Bluemap containerport wrong with container 1.6.3

### ISSUE THREAD

**Issue by charims** [qumine/charts#10]
The bluemap containerport was updated to 9090 in 1.6.3

![image](https://user-images.githubusercontent.com/13107565/143476429-60fbc11f-ae00-4e9a-afa9-e25b5a12d4a1.png)

but the containerport in the helmchart still uses 8081.
 
Thanks for the great charts and containers!

**Comment by 0SkillAllLuck** [comment]
Thanks for your contribution, will be resolved with 0.1.902 of the chart
